language: go

sudo: false

go:
- "1.11.x"
- tip

env:
  - GO111MODULE=on
arch:
  - amd64
  - ppc64le

install: true

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - ulimit -n 2048 ; go test -v ./... -covermode=count -coverprofile=profile.cov.tmp
  - cat profile.cov.tmp | grep -v "generated" | grep -v "admin" > profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
